[project]
name = "passwordsandhashing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.129.0",
    "python-jose[cryptography]>=3.5.0",
]
